{% set name = "universions" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3030ee9471f5c61a194fe895c273c3f411b93cfbfacfb1374c0904f27d60414b


build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - universions = universions:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - universions
  commands:
    - universions --help

about:
  home: https://github.com/fabiencelier/universions
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Get version of other tools.'
  doc_url: https://universions.readthedocs.io/
  dev_url: https://github.com/fabiencelier/universions

extra:
  recipe-maintainers:
    - fabiencelier
